// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZ_B1iqiqW7TyABIyRF-3kFlimJ501Co',
    appId: '1:343378783251:web:4e8f59cab12f6ae0ab23e6',
    messagingSenderId: '343378783251',
    projectId: 'cordillera-moviles',
    authDomain: 'cordillera-moviles.firebaseapp.com',
    storageBucket: 'cordillera-moviles.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB96o-iYwyBxa0xy_ivBccT0f8PTeo-Zk',
    appId: '1:343378783251:android:2123fec9965f9900ab23e6',
    messagingSenderId: '343378783251',
    projectId: 'cordillera-moviles',
    storageBucket: 'cordillera-moviles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVK625ekewGbGEj-9-gsx-o-MufpDr-o',
    appId: '1:343378783251:ios:79426186416cb435ab23e6',
    messagingSenderId: '343378783251',
    projectId: 'cordillera-moviles',
    storageBucket: 'cordillera-moviles.firebasestorage.app',
    iosBundleId: 'com.example.loginPractica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVK625ekewGbGEj-9-gsx-o-MufpDr-o',
    appId: '1:343378783251:ios:79426186416cb435ab23e6',
    messagingSenderId: '343378783251',
    projectId: 'cordillera-moviles',
    storageBucket: 'cordillera-moviles.firebasestorage.app',
    iosBundleId: 'com.example.loginPractica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiZ_B1iqiqW7TyABIyRF-3kFlimJ501Co',
    appId: '1:343378783251:web:164aaf8e1404ef2aab23e6',
    messagingSenderId: '343378783251',
    projectId: 'cordillera-moviles',
    authDomain: 'cordillera-moviles.firebaseapp.com',
    storageBucket: 'cordillera-moviles.firebasestorage.app',
  );
}
